# Enable C++ support
language: cpp

stages:
  - prebuild
  - build
  - sanitizers
  - deploy

jobs:
  include:
    - stage: prebuild
      name: "Verify code formating"
      dist: xenial
      before_install:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
        - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
        - sudo apt-get update -qq
        - sudo apt-get install -y --allow-unauthenticated clang-format-10
      script: ./tools/run-clang-format.py -r src test bench
    - stage: prebuild
      name: "Static analysis"
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: TIDY=clang-tidy-10
      before_install:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
        - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
        - sudo apt-get update -qq
        - sudo apt-get install -y --allow-unauthenticated clang-tidy-10
      script: ./tools/tidy
    - stage: build
      name: "Clang 10"
      os: linux
      sudo: required
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env:
        - COMPILER=clang++-10
      before_install:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
        - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
        - sudo apt-get update -qq
        - sudo apt-get install -y --allow-unauthenticated clang++-10
      script: ./build
    - stage: build
      name: "GCC 10"
      sudo: required
      services:
        - docker
      before_install:
        - docker run -dit --name gcc -v $(pwd):/src petersonjm1/gcc bash
      script:
        - docker exec -it gcc bash -c "cd src;COMPILER=g++ ./build"
    - stage: build
      name: "Emscripten"
      sudo: required
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src petersonjm1/emscripten bash
      script:
        - docker exec -it emscripten bash -c "./tools/build-emscripten"
    - stage: sanitizers
      name: "Address sanitizer"
      os: linux
      sudo: required
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env: COMPILER=clang++-10
      before_install:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
        - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
        - sudo apt-get update -qq
        - sudo apt-get install -y --allow-unauthenticated clang++-10
      script: ./tools/build-asan
    - stage: sanitizers
      name: "Thread sanitizer"
      os: linux
      sudo: required
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env: COMPILER=clang++-10
      before_install:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
        - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
        - sudo apt-get update -qq
        - sudo apt-get install -y --allow-unauthenticated clang++-10
      script: ./tools/build-tsan
    - stage: sanitizers
      name: "Undefined behavior sanitizer"
      os: linux
      sudo: required
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env: COMPILER=clang++-10
      before_install:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
        - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
        - sudo apt-get update -qq
        - sudo apt-get install -y --allow-unauthenticated clang++-10
      script: ./tools/build-ubsan
    - stage: deploy
      name: "Deploy to Github Pages"
      if: branch = master
      sudo: required
      services:
        - docker
      before_install:
        - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
        - docker run -dit --name emscripten -v $(pwd):/src petersonjm1/emscripten bash
      script:
        - docker exec -it emscripten bash -c "./tools/build-release-emscripten"
        - docker exec -it emscripten bash -c "./tools/deploy"
      deploy:
        provider: pages:git
        edge: true
        local_dir: artifacts/ReleaseEmscripten/deploy
        commit_message: Deploy from %{git_branch} at %{git_sha}
        deploy_key: deploy_key
