#!/bin/sh
set -e
if [ ! -d artifacts ]; then
  mkdir artifacts
fi
cd artifacts
if [ ! -d Release ]; then
  mkdir Release
fi
cd Release
if [ -n "$COMPILER" ]; then
  echo "COMPILER is defined, use it: CXX=$COMPILER"
  export CXX=$COMPILER
fi
if [ -z "$CXX" ]; then
  echo "CXX is not set, using clang by default"
  export CXX=clang++
fi

CMAKE_ADDITIONAL_ARGS=""
if [ "$CXX" = "em++" ]; then
  CMAKE_ADDITIONAL_ARGS=-DEMSCRIPTEN=ON
fi

cmake -DCMAKE_BUILD_TYPE=Release $CMAKE_ADDITIONAL_ARGS ../.. -GNinja
ninja

if [ "$CXX" = "em++" ]; then
  node test/tests.js
else
  ./test/tests
fi

cd ../..

if [ -n "$SIZE_NAME" ]; then
  ./tools/record_size.py "$SIZE_NAME" artifacts/Release/src/libbinarily.a
fi
