#!/bin/sh
set -e
if [ ! -d artifacts ]; then
  mkdir artifacts
fi
cd artifacts
if [ ! -d ReleaseEmscripten ]; then
  mkdir ReleaseEmscripten
fi
cd ReleaseEmscripten
if [ -n "$COMPILER" ]; then
  echo "COMPILER is defined, use it: CXX=$COMPILER"
  export CXX=$COMPILER
fi
if [ -z "$CXX" ]; then
  export CXX=em++
fi
cmake -DCMAKE_BUILD_TYPE=Release -DEMSCRIPTEN=ON ../.. -GNinja
ninja
node test/tests.js
cd ../..

if [ -n "$SIZE_NAME" ]; then
  ./tools/record_size.py "$SIZE_NAME" artifacts/ReleaseEmscripten/src/libbinarily.a
fi
