#!/bin/sh
set -e
if [ ! -d artifacts ]; then
  mkdir artifacts
fi
cd artifacts
if [ ! -d DebugEmscripten ]; then
  mkdir DebugEmscripten
fi
cd DebugEmscripten
if [ -n "$COMPILER" ]; then
  echo "COMPILER is defined, use it: CXX=$COMPILER"
  export CXX=$COMPILER
fi
if [ -z "$CXX" ]; then
  export CXX=em++
fi
cmake -DCMAKE_BUILD_TYPE=Debug -DEMSCRIPTEN=ON ../..
make
node test/tests.js
cd ../..
