#!/bin/sh
if [ -d artifacts/Release/deploy ]; then
  rm artifacts/Release/deploy/*
else
  mkdir artifacts/Release/deploy
fi
cp artifacts/Release/src/binarily.html artifacts/Release/deploy/index.html
cp artifacts/Release/src/*.js artifacts/Release/deploy
cp artifacts/Release/src/*.wasm artifacts/Release/deploy
cp artifacts/Release/src/*.svg artifacts/Release/deploy
cp artifacts/Release/src/*.png artifacts/Release/deploy
cp artifacts/Release/src/*.ico artifacts/Release/deploy
