#!/bin/sh
if [ -n "$TIDY" ]; then
  echo "TIDY is defined, use it: $TIDY"
fi
if [ -z "$TIDY" ]; then
  export TIDY=clang-tidy
fi
if [ $# -eq 0 ] ; then
  FILES=`git diff  --name-only --diff-filter=AMR '*.cpp' | xargs`
  if [ -z "$FILES" ]; then
    FILES="src/*.cpp test/*.cpp"
  fi
else
  FILES="$1"
fi
echo Checking $FILES
$TIDY $FILES --quiet --fix --format-style=file -config='' -- -std=c++17 -Ithirdparty/catch/include -Ithirdparty/gsl -Ithirdparty/benchmark/include -Ithirdparty/fmt/include -Ithirdparty/nlohmann -Isrc
