#!/bin/sh
if [ -z "$1" ]
  then
    echo 'Please supply a command to watch'
    exit 1
fi
uname=`uname`
if [ "$uname" = 'Linux' ]; then
  ag -l --ignore-dir artifacts | entr time -f "Total time: %e seconds" "$@"
else
  ag -l --ignore-dir artifacts | entr "$@"
fi
